### ISSUE TITLE
[Refact] 코드 정리 + 리팩토링

### ISSUE THREAD

**Issue by devKangMinHyeok** [mipsSimulatorUNIST/simulator#107]
## Description
simulator repo의 소스코드들 중에서 코드 정리가 필요하거나 리팩토링이 필요한 부분을 개선

<br>

## Todo

**코드 정리**
- [x] console.log 삭제 
- [x] 쓸모없는 주석 삭제
- [x] 쓰이지 않는 코드 삭제

**리팩토링**
- [x] 타입 지정되어 있지 않은 것들 타입 지정
- [x] 한 폴더에 존재하는 interface 상단으로 foward declaration
- [x] type과 interface 통일
- [x] 불필요한 문맥 빼기
- [x] 명령형 -> 함수형
- [x] 불변성 추가
- [x] typescript alias

<br>

## ETC
기타 참고 사항이 있으면 작성해주세요.
