### ISSUE TITLE
[docs] new mapping table 관련 readme 작성

### ISSUE THREAD

**Issue by limetree06** [mipsSimulatorUNIST/simulator#114]
## Description
이슈에 대한 설명을 작성해주세요

<br>

## Todo
- [x] mapping detail 부분 수정 내용 추가 - mapping detail sample
- [x] changes에 바뀐 버전부터 뭐 바뀌었는지 명시
- [x] stable한 버전 넘버 바꾸기
- [x] usage에 import하는 방법 명시

<br>

## ETC
기타 참고 사항이 있으면 작성해주세요.
