### ISSUE TITLE
[Feature] Parsing assembly file (*.s) into list

### ISSUE THREAD

**Issue by haejunejung** [mipsSimulatorUNIST/simulator#19]
## Description
어셈블리 파일을 리스트로 변환
기존에 없던 Error case들 추가

<br>
## Todo

- [x] try ~ catch 로 Error 관리 추가
- [x] 파일 경로가 존재하지 않을 때 Error message 추가
- [x] 파일 경로가 존재하지만, 내용이 없을 때 Error message 추가

<br>

## ETC
한 번 머지된 후에 수정된 부분 수정을 위해 새롭게 이슈 생성함
