### ISSUE TITLE
[FIX] makeSymbolTable 순수함수로 전환

### ISSUE THREAD

**Issue by devKangMinHyeok** [mipsSimulatorUNIST/simulator#22]
## Description
현재 방식은 
SYMBOL_TABLE,
textSeg,
dataSeg,
dataSectionSize,
textSectionSize
이들을 전역변수로 선언하여 참조 및 변경된다.
이때 생길 수 있는 부작용은 다음과 같다.

1. **전역변수 초기화 상태 보장 여부 불확실**
전역변수가 각 테스트케이스에 대해서 reset된 상태로 시작하는지 보장하기 어렵고, 이를 위해 매번 reset 여부를 확인하고 기능 코드가 동작해야한다.

2. **외부 파일 접근은 Read Only로만 가능**
외부 파일에서 이 변수들에 접근하려고 할때, Read Only로만 가능하기 때문에 변수 변경을 위한 추가적인 함수들이 필요하게 된다.

3. **Unit Test의 어려움**
테스트 케이스를 작성하고 실제 단위 테스트를 진행하는 과정에서 순수함수의 경우는 input에 대한 output을 바로 비교하면 된다.
하지만 이렇게 전역변수와 side effect를 사용하여 진행하면, 함수 실행 후 전역변수를 참조하여 테스트해야하는 번거로움으로 코드량이 증가할 수 있다. 또한 함수 실행 후 참조이다보니, 예측할 수 없는 부작용도 발생할 수 있다.

이에 따라 순수함수로 변경하는 방법을 채택하였다.

<br>

## Todo

- [x] state.js 파일 제거
- [x] state.js의 변수들을 사용하는 곳에서는 함수 스코프 내에서 변수를 선언하여 순수함수로 기능하도록 변경
- [x] ~~contants.js의 SYMBOL_TABLE도 마찬가지로 전역으로 사용되는 배열에서, makeSymbolTable의 output 중 하나로 변경~~
- [x] SYMBOL_TABLE은 다른 함수에서도 참조하고 있으므로 변경하지 않는 것으로 진행

<br>
