### ISSUE TITLE
[Feature] ts 개발 환경 세팅

### ISSUE THREAD

**Issue by limetree06** [mipsSimulatorUNIST/simulator#40]
## Description
이슈에 대한 설명을 작성해주세요
ts로 개발을 진행하기 위한 기본적인 환경 세팅

<br>
## Todo

- [x] ts 개발환경 세팅 알아보기
- [x] 기본 스켈리톤 코드 ts로 작성
- [x] main.ts 변경
- [x] function.ts 변경
- [x] constant.ts 변경
- [ ] tsconfig.json 에 "allowJs":  false로 변경해서 테스트

<br>

## ETC
기타 참고 사항이 있으면 작성해주세요.
