### ISSUE TITLE
[Feature] CI 구축

### ISSUE THREAD

**Issue by devKangMinHyeok** [mipsSimulatorUNIST/simulator#47]
## Description
테스트 자동화를 위한 CI 구축
<br>

## Todo
- [x] 폴더 구조 재구성
- [x] ESLint 적용
- [x] Prettier 적용
- [x] CI yml 스크립트 작성
- [x] test Code 파일 작성
- [x] build 전, merge 막기 설정
- [x] babel 설정

<br>
