### ISSUE TITLE
[Feature] assignment2 ts 파일 변환

### ISSUE THREAD

**Issue by limetree06** [mipsSimulatorUNIST/simulator#51]
## Description
이슈에 대한 설명을 작성해주세요
<br>
## Todo
- [x] parse.py 변환
- [x] initialize.py 변환
- [ ] 함수 별 테스트 코드 작성 + cl 이용해서 테스트

<br>

## ETC
기타 참고 사항이 있으면 작성해주세요.
