### ISSUE TITLE
[Feature] Coverage 확인 github page 호스팅

### ISSUE THREAD

**Issue by devKangMinHyeok** [mipsSimulatorUNIST/simulator#52]
## Description
jest 기능을 이용해서 coverage html 파일 생성 가능
이 html으로 github page 이용해서 호스팅
=> 회의 때 의논예정, 먼저 따로 브랜치 파서 작업

<참고>
https://davidyang2149.dev/front-end/github-actions%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-gh-pages-%EC%9E%90%EB%8F%99-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0/

<br>
## Todo

- [x] github page 호스팅
- [x] jest.config 작성
- [x] github publish 스크립트

<br>

<img width="957" alt="image" src="https://user-images.githubusercontent.com/44657722/212543216-9c62fe39-a4b8-4fc2-9c5a-208359a0d0dc.png">
