### ISSUE TITLE
[Feature] react에서 npm을 사용 시 fs 관련 에러 핸들링을 위한 readme 수정

### ISSUE THREAD

**Issue by bams11** [mipsSimulatorUNIST/simulator#75]
## Description
react 프로젝트에서 해당 simulator를 설치하여 사용했을 때 fs관련 에러 발생. 이를 핸들링하기 위한 설명을 readme에 추가
<br>
## Todo

- [ ] 문제 상황 요약 (webpack 버전 관련 이슈 참고할 수 있도록 링크 추가)
- [ ] 변경해야할 설정 추가 (package.json, webpack.config.js 등)
- [ ] 어떤 식으로 파일을 불러올 수 있을지 예시함수 추가 (fetch 이용)
<img width="1315" alt="reactError" src="https://user-images.githubusercontent.com/64965613/216809659-1dde2240-5461-45b2-948a-bff631e5c528.png">

<br>

## ETC
다음 단계 목표로 Npm 자체에 예시함수 추가하기
