### ISSUE TITLE
[Feature] makeSymbolTable 제작

### ISSUE THREAD

**Issue by devKangMinHyeok** [mipsSimulatorUNIST/simulator#8]
## Description
input : list 형태의 어셈블리 명령어
output : dictionary(map) 형태의 symbol, list형태의 testSeg, dataSeg
<br>
## Todo

- [x] 'dataSeg'에 data 저장
- [x] 'textSeg'에 text 저장
- [x] 각 label로 정해진 주소값 매핑해서 딕셔너리 형태로 반환
- [x] 10진수를 16진수로 변환 후 패딩하는 함수 제작
- [x] symbolTableAddEntry 함수 제작
<br>
