### ISSUE TITLE
[Feature] Parsing an assembly file(*.s) into a list

### ISSUE THREAD

**Issue by haejunejung** [mipsSimulatorUNIST/simulator#9]
## Description
input : assembly file(*.s)
output : 리스트 형태로 변환
ex) 
['\t.data', 'data1:\t.word\t100', 'data2:\t.word\t200', ... ]
  <br>
## Todo

- [x] function.js → makeInput 함수 제작
- [x] test.js → makeInput 함수에서 input으로 리스트 불러오기
- [x] assembler.js → makeSymbolTable 함수에서 리스트 형태로 들어오는지 확인

<br>

## ETC
기타 참고 사항이 있으면 작성해주세요.
