### ISSUE TITLE
[Feature] improve mappingTable

### ISSUE THREAD

**Issue by limetree06** [mipsSimulatorUNIST/simulator#96]
## Description
이슈에 대한 설명을 작성해주세요.
reactGUI 하이라이트 기능 업그레이드를 위한 추가 기능 제작

<br>

## Todo
- [x]  mapping Table 코드 이해
- [x]  함수명을 해당 PC 값에 매핑
- [x]  data section 을 binary file 하단 data 부분에 mapping
- [x]  data section size, text section size 를 .data, .text에 맵핑

<br>

## ETC
기타 참고 사항이 있으면 작성해주세요.
